Repository Kojotm/TotallyNotMonopoly, pull requests merged in 2021-10, with the labels that each got.

#10 Added backend structure
  TotallyNotMonopolyAPI/Model/Class1.cs
  TotallyNotMonopolyAPI/Model/Model.csproj
  TotallyNotMonopolyAPI/Persistence/Class1.cs
  TotallyNotMonopolyAPI/Persistence/Persistence.csproj
  TotallyNotMonopolyAPI/Services.Test/Services.Test.csproj
  TotallyNotMonopolyAPI/Services.Test/UnitTest1.cs
  TotallyNotMonopolyAPI/Services/Class1.cs
  TotallyNotMonopolyAPI/Services/Services.csproj
  TotallyNotMonopolyAPI/TotallyNotMonopolyAPI.sln
  TotallyNotMonopolyAPI/WebAPI/Controllers/WeatherForecastController.cs
  TotallyNotMonopolyAPI/WebAPI/Program.cs
  TotallyNotMonopolyAPI/WebAPI/Properties/launchSettings.json
  TotallyNotMonopolyAPI/WebAPI/Startup.cs
  TotallyNotMonopolyAPI/WebAPI/WeatherForecast.cs
  TotallyNotMonopolyAPI/WebAPI/WebAPI.csproj
  TotallyNotMonopolyAPI/WebAPI/appsettings.Development.json
  TotallyNotMonopolyAPI/WebAPI/appsettings.json
Labels: enhancement

#14 Install Angular material to UI
  TotallyNotMonopolyUI/package-lock.json
  TotallyNotMonopolyUI/package.json
  TotallyNotMonopolyUI/src/index.html
  TotallyNotMonopolyUI/src/styles.scss
Labels: essential

#19 Read JSON File
  TotallyNotMonopolyAPI/Model/Asset/json1.json
  TotallyNotMonopolyAPI/Model/Class1.cs
  TotallyNotMonopolyAPI/Model/Class2.cs
  TotallyNotMonopolyAPI/Model/Model.csproj
  TotallyNotMonopolyAPI/Services.Test/Services.Test.csproj
  TotallyNotMonopolyAPI/Services.Test/UnitTest1.cs
  TotallyNotMonopolyAPI/WebAPI/Program.cs
  TotallyNotMonopolyAPI/WebAPI/WebAPI.csproj
Labels: enhancement, test

#20 Create player info cards
  TotallyNotMonopolyUI/src/app/app.module.ts
  TotallyNotMonopolyUI/src/app/game-table/game-table.component.html
  TotallyNotMonopolyUI/src/app/game-table/game-table.component.scss
  TotallyNotMonopolyUI/src/app/game-table/game-table.component.ts
  TotallyNotMonopolyUI/src/app/game-table/upgrade-menu.html
Labels: enhancement
